version: "3.5"
services:
  rocketpool.public.dappnode.eth:
    image: "rocketpool.public.dappnode.eth:0.1.0"
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: v1.7.5
    volumes:
      - "rocketpool:/rocketpool"
    environment:
      - NETWORK=prater
      - WALLET_PASSWORD=
      - EXTRA_OPTS=
    restart: unless-stopped
volumes:
  rocketpool: {}
